### ISSUE TITLE
ImportError: cannot import name DatabaseManager

### ISSUE THREAD

**Issue by rimantoro** [sdispater/orator#123]
I'm updating my issue.

Now, instead of using Flask. I'm using a simple Pycnic framework with Orator. This is my installation

* Virtualenv
* Orator 0.9.3

Somehow Orator suddenly cannot import all of the module. This is how I reproduce this issue :

* Create a new virtual environment and clone my project [here](https://github.com/rimantoro/my-pycnic-svc).
* Install requirement ```pip install -r requirements.txt```.
* Run gunicorn ```gunicorn app:app --bind 0.0.0.0:8000 --reload``` this should be run well.
* Change to branch __dev-migration__ and run gunicorn again, it raised an error below
```bash
[2016-12-29 14:05:43 +0000] [3230] [INFO] Starting gunicorn 19.6.0
[2016-12-29 14:05:43 +0000] [3230] [INFO] Listening at: http://0.0.0.0:8000 (3230)
[2016-12-29 14:05:43 +0000] [3230] [INFO] Using worker: sync
[2016-12-29 14:05:43 +0000] [3235] [INFO] Booting worker with pid: 3235
[2016-12-29 14:05:43 +0000] [3235] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/imanovski/www/rimantoro/labs/python/venv_hedwig/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 557, in spawn_worker
    worker.init_process()
  File "/home/imanovski/www/rimantoro/labs/python/venv_hedwig/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/home/imanovski/www/rimantoro/labs/python/venv_hedwig/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 136, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/imanovski/www/rimantoro/labs/python/venv_hedwig/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/imanovski/www/rimantoro/labs/python/venv_hedwig/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/home/imanovski/www/rimantoro/labs/python/venv_hedwig/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/imanovski/www/rimantoro/labs/python/venv_hedwig/local/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/home/imanovski/www/rimantoro/labs/python/venv_hedwig/hedwig/app.py", line 6, in <module>
    from handlers import client, messaging
  File "/home/imanovski/www/rimantoro/labs/python/venv_hedwig/hedwig/handlers/client.py", line 6, in <module>
    from models.client import Client as ClientModel
  File "/home/imanovski/www/rimantoro/labs/python/venv_hedwig/hedwig/models/client.py", line 1, in <module>
    from base import CrudBase, AuthenticableBase
  File "/home/imanovski/www/rimantoro/labs/python/venv_hedwig/hedwig/models/base.py", line 1, in <module>
    from db import db
  File "/home/imanovski/www/rimantoro/labs/python/venv_hedwig/hedwig/db.py", line 1, in <module>
    from orator import DatabaseManager
ImportError: cannot import name DatabaseManager
[2016-12-29 14:05:43 +0000] [3235] [INFO] Worker exiting (pid: 3235)
[2016-12-29 14:05:43 +0000] [3230] [INFO] Shutting down: Master
[2016-12-29 14:05:43 +0000] [3230] [INFO] Reason: Worker failed to boot.
``` 
* Then I checkout to master branch and run the server it also raise same error, which should be fine previously

Is there is known issue for using Orator within virtualenv ?

Thanks.

__My previous comment :__

> Hi,
> 
> I'm installing orator via flask-orator and always raise ImportError when I try to run the server. Below is the trace
> 
> ```bash
> /home/imanovski/www/rimantoro/labs/python/venv_flask/local/lib/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.script is deprecated, use flask_script instead.
>   .format(x=modname), ExtDeprecationWarning
> /home/imanovski/www/rimantoro/labs/python/venv_flask/local/lib/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.migrate is deprecated, use flask_migrate instead.
>   .format(x=modname), ExtDeprecationWarning
> /home/imanovski/www/rimantoro/labs/python/venv_flask/local/lib/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.sqlalchemy is deprecated, use flask_sqlalchemy instead.
>   .format(x=modname), ExtDeprecationWarning
> Traceback (most recent call last):
>   File "manage.py", line 6, in <module>
>     from application import create_app
>   File "/home/imanovski/www/rimantoro/labs/python/venv_flask/projects/hedwig/application/__init__.py", line 22, in <module>
>     from flask_orator import Orator
>   File "/home/imanovski/www/rimantoro/labs/python/venv_flask/local/lib/python2.7/site-packages/flask_orator/__init__.py", line 4, in <module>
>     from orator import DatabaseManager, Model as BaseModel
> ImportError: cannot import name DatabaseManager
> ```
> 
> Where is DatabaseManager should come from ? 
> 
> I'm just following the Orator example and I thought this should be there inside Orator.
>

**Comment by sdispater** [comment]
What is the version of both orator and flask-orator?

Also, can you give me a sample of the code you wrote?

**Comment by rimantoro** [comment]
I have a manage.py in my root project path also I have "application" folder where I put my project core and create the app object inside application folder

[project_path]/manage.py
```python
# coding: utf-8
import os
import glob2
from flask.ext.script import Manager
from application import create_app

# Used by app debug & livereload
PORT = 5000

app = create_app()
manager = Manager(app)
```

[project_path]/application/__init__.py
```python
def create_app():
    """Create Flask app."""
    ...

    # Register components
    register_db(app)
    ...
...
def register_db(app):
    """Register models."""
    from flask_orator import Orator
    db = Orator(app)
...
```

I even not using the "db" yet, but it always return an error I mention before.

**Comment by rimantoro** [comment]
@sdispater I'm updating my comment with a steps for reproduce the issue

**Comment by sdispater** [comment]
Thanks. I will take a look at it when I have the time.

**Comment by sdispater** [comment]
After a quick look: your problem comes from the `orator.py` file because when you do `from orator import db`, Python will use the `orator.py` file instead of the library. And when you go back to `master` a `orator.pyc` file still exists which Python picks up that's why you still see the error.

**Comment by rimantoro** [comment]
@sdispater 

Ok, there is one issue. But in my dev-migration branch why the "DatabaseManager" raised an ImportError even I have successfully install orator ?

**Comment by rimantoro** [comment]
I'm already find, why I cannot start my gunicorn server. I'm deleting my orator.py file and it run well. Not yet know why the file caused an ImportError when starting the server.

**Comment by denislins** [comment]
This has just happened to me. I spent ~2 hours fiddling around until I managed to solve it :(

Could we please change the docs to reflect this? I think it would help a lot of people trying to use the library.
