### ISSUE TITLE
Model returned from .create() incorrectly reports associated model for (unset) belongs_to relation. Hacky workaround works for sqlite3/mysql but not postgres

### ISSUE THREAD

**Issue by mattcl** [sdispater/orator#160]
```python
# orator 0.9.5
from orator import DatabaseManager, Model
from models.comment import Comment

config = {
    'sqlite': {
        'driver': 'sqlite',
        'database': 'sandbox.sqlite3'
    }
}

db = DatabaseManager(config)
Model.set_connection_resolver(db)

db.table('comments').delete()

comment1 = Comment.create(body='derp1')
comment2 = Comment.create(body='derp2')
comment2.parent().associate(comment1)

comment2.save()
comment2.fresh()

# parent set
print(comment2.parent()._query.to_sql())
# => SELECT * FROM "comments" WHERE "comments"."id" = ?

# passes
assert comment2.parent == comment1

# no parent yet
comment3 = Comment.create(body='derp3')
print(comment3.parent()._query.to_sql())
# => SELECT * FROM "comments"
#    ^ Notice no 'where' clause so this is going to return all rows

# even worse, this passes because the belongs to returns self._query.first()
assert comment3.parent.id == comment1.id

# expected because it's null in the table.
assert not hasattr(comment3, 'parent_id')
```
So this behavior is not observed if you do the following hacky workaround.
```python
# fetch a new instance of the object
comment3 = Comment.find(comment3.id)

# note: comment3.fresh() is not sufficient

# this is now correct (probably something to do with the instantiation?)
assert comment3.parent == None

# interestingly enough, 'assert comment3.parent is None' doesn't work while '==' does.
```
*however*, using postgres (with psycopg2==2.7.1) yields the following error
```
Traceback (most recent call last):
  File "/home/matt/.virtualenvs/orator-sandbox/lib/python3.4/site-packages/orator/connections/connection.py", line 31, in _run
    result = wrapped(self, query, bindings, *args, **kwargs)
  File "/home/matt/.virtualenvs/orator-sandbox/lib/python3.4/site-packages/orator/connections/connection.py", line 199, in select
    cursor.execute(query, bindings)
  File "/home/matt/.virtualenvs/orator-sandbox/lib/python3.4/site-packages/psycopg2/extras.py", line 144, in execute
    return super(DictCursor, self).execute(query, vars)
psycopg2.DataError: invalid input syntax for integer: "="
LINE 1: SELECT * FROM "comments" WHERE "comments"."id" = '=' LIMIT 1
                                                         ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "foo.py", line 46, in <module>
    assert comment3.parent == None
  File "/home/matt/.virtualenvs/orator-sandbox/lib/python3.4/site-packages/orator/orm/relations/wrapper.py", line 34, in _get_results
    return self._relation.get_results()
  File "/home/matt/.virtualenvs/orator-sandbox/lib/python3.4/site-packages/orator/orm/relations/belongs_to.py", line 37, in get_results
    return self._query.first()
  File "/home/matt/.virtualenvs/orator-sandbox/lib/python3.4/site-packages/orator/orm/builder.py", line 170, in first
    return self.take(1).get(columns).first()
  File "/home/matt/.virtualenvs/orator-sandbox/lib/python3.4/site-packages/orator/orm/builder.py", line 198, in get
    models = self.get_models(columns)
  File "/home/matt/.virtualenvs/orator-sandbox/lib/python3.4/site-packages/orator/orm/builder.py", line 439, in get_models
    results = self.apply_scopes().get_query().get(columns).all()
  File "/home/matt/.virtualenvs/orator-sandbox/lib/python3.4/site-packages/orator/query/builder.py", line 1058, in get
    results = self._processor.process_select(self, self._run_select())
  File "/home/matt/.virtualenvs/orator-sandbox/lib/python3.4/site-packages/orator/query/builder.py", line 1074, in _run_select
    not self._use_write_connection
  File "/home/matt/.virtualenvs/orator-sandbox/lib/python3.4/site-packages/orator/connections/connection.py", line 34, in _run
    e, query, bindings, wrapped
  File "/home/matt/.virtualenvs/orator-sandbox/lib/python3.4/site-packages/orator/connections/connection.py", line 317, in _try_again_if_caused_by_lost_connection
    raise QueryException(query, bindings, e)
orator.exceptions.query.QueryException: invalid input syntax for integer: "="
LINE 1: SELECT * FROM "comments" WHERE "comments"."id" = '=' LIMIT 1
                                                         ^
 (SQL: SELECT * FROM "comments" WHERE "comments"."id" = %s LIMIT 1 (['=']))
```

It looks like because the underlying where clause is 
```python
self._query.where('%s.%s' % (table, self._other_key), '=', getattr(self._parent, self._foreign_key))
```
it ends up passing None to psycopg2 which somehow results in an '=' being inserted in place of the value. This behavior is *not* observed when using PyMySQL or the sqlite3 driver. I'm guessing that issue may be more to do with psycopg2, and I'll consider opening a ticket with that project if that's the case.

**However**, the issue of a new object returned from `.create` returning the first row from the parent table as its parent is a bug with this library (and can lead to undesired behavior where an object is returned from the belongs_to relation where you weren't expecting it/doesn't actually own you).

**Comment by mattcl** [comment]
I should add the associated model and migration

Model:
```python
from orator import Model
from orator.orm import belongs_to, has_many


class Comment(Model):
    __fillable__ = ['body']

    @belongs_to('parent_id')
    def parent(self):
        return Comment

    @has_many
    def children(self):
        return Comment
```

Migration:
```python
from orator.migrations import Migration


class CreateCommentsTable(Migration):

    def up(self):
        with self.schema.create('comments') as table:
            table.increments('id')
            table.string('body')
            table.big_integer('parent_id').nullable()
            table.timestamps()

    def down(self):
        """
        Revert the migrations.
        """
        self.schema.drop('comments')
```

**Comment by sdispater** [comment]
Thanks for the detailed explanation.

I will look into it and get  back to you.

**Comment by sdispater** [comment]
Ok, I see.

The thing is `create()` will only create the entry in the database without populating the model's attributes. So when you do

```python
comment3 = Comment.create(body='derp3')
```

the `parent_id` attribute is not set on the model which causes the `belongs_to` relation to not set the proper constraint.

Maybe `create()` should get a fresh instance automatically. It would also be useful if you have default values for the table.

For now, a workaround would be:

```python
comment3 = Comment.create(body='derp3').fresh()
```

**Comment by mattcl** [comment]
Ah, I see I misunderstood how .fresh() worked. I assumed it was like ActiveRecord's .reload() where it would do it in place. The postgres issue still stands, however, even with .fresh().

**Comment by sdispater** [comment]
Commit 6fd2096c53c75b5adb6f08d183608b96312a28af should fix the issue

**Comment by sdispater** [comment]
@mattcl Did commit 6fd2096c53c75b5adb6f08d183608b96312a28af fix the issue for you?

**Comment by mattcl** [comment]
@sdispater yes, that looks like it resolves the problem. Thanks for the quick turnaround!
