### ISSUE TITLE
Error  orator.exceptions.query.QueryException: (2013, 'Lost connection to MySQL server during  query'

### ISSUE THREAD

**Issue by AnthraxisBR** [sdispater/orator#233]
I'm using that package in my local enviroment, but when using gcloud sdk to deploy this app in the cloud, for the first time every looks like ok, but after some time without no connection i'm come to take de following error:

```
2018-05-08 00:43:33 default[20180507t093010]  [2018-05-08 00:43:33,816] ERROR in app: Exception on /login [POST]
2018-05-08 00:43:33 default[20180507t093010]  Traceback (most recent call last):    File "/env/lib/python3.6/site-packages/orator/connections/connection.py", line 31, in _run      result = wrapped(self, query, bindings, *args, **kwargs)    File "/env/lib/python3.6/site-packages/orator/connections/connection.py", line 199, in select      cursor.execute(query, bindings)    File "/env/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute      result = self._query(query)    File "/env/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query      conn.query(q)    File "/env/lib/python3.6/site-packages/pymysql/connections.py", line 892, in query      self._execute_command(COMMAND.COM_QUERY, sql)    File "/env/lib/python3.6/site-packages/pymysql/connections.py", line 1122, in _execute_command      raise err.InterfaceError("(0, '')")  pymysql.err.InterfaceError: (0, '')
```
Resuming, I cannot connect again, unless I made a new deploy, 

I'm using flask ,but without flask-orator, and in the last stable version 0.9.7.

I alread have seen de issue https://github.com/sdispater/orator/issues/57, but it doesn't works for me.

The database is Google SQL, but everything work fine in local enviroment, the problem is the app engine is closing the connection after a certain time, I already have tryied so much solutions but no one of theirs  works, I'm looking for help to solve this problem

Orator 0.9.7
Flask  1.0.2
Python 3.6.4

PS.: Sorry for the english, I'm doesn't have pratice

**Comment by josephmancuso** [comment]
This may have been fixed. We recently made changes to a connection issue. Can you try to pip install from the 0.9 branch on this repo and see if that fixes the problem?

**Comment by zhanghaofei** [comment]
```
2019-03-07 13:27:13,374 [ThreadPoolExecutor-0_0:140173442423528] [__main__:158] [ERROR]- 按节收费异常：18
Traceback (most recent call last):
  File "/opt/project/catalog_charge/main.py", line 148, in catalog_charge
    with youhong.transaction():
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.6/site-packages/orator/connections/connection.py", line 288, in transaction
    self.begin_transaction()
  File "/usr/lib/python3.6/site-packages/orator/connections/mysql_connection.py", line 41, in begin_transaction
    self._connection.autocommit(False)
  File "/usr/lib/python3.6/site-packages/pymysql/connections.py", line 753, in autocommit
    self._send_autocommit_mode()
  File "/usr/lib/python3.6/site-packages/pymysql/connections.py", line 770, in _send_autocommit_mode
    self.escape(self.autocommit_mode))
  File "/usr/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in _execute_command
    raise err.InterfaceError("(0, '')")
pymysql.err.InterfaceError: (0, '')
2019-03-07 13:27:13,486 [ThreadPoolExecutor-0_0:140173442423528] [__main__:158] [ERROR]- 按节收费异常：19
Traceback (most recent call last):
  File "/opt/project/catalog_charge/main.py", line 148, in catalog_charge
    with youhong.transaction():
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.6/site-packages/orator/connections/connection.py", line 288, in transaction
    self.begin_transaction()
  File "/usr/lib/python3.6/site-packages/orator/connections/mysql_connection.py", line 41, in begin_transaction
    self._connection.autocommit(False)
  File "/usr/lib/python3.6/site-packages/pymysql/connections.py", line 753, in autocommit
    self._send_autocommit_mode()
  File "/usr/lib/python3.6/site-packages/pymysql/connections.py", line 770, in _send_autocommit_mode
    self.escape(self.autocommit_mode))
  File "/usr/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in _execute_command
    raise err.InterfaceError("(0, '')")
pymysql.err.InterfaceError: (0, '')
```

in `def _caused_by_lost_connection(self, e)`,e='(0,\\'\\'))' and not in message

**Comment by securityBoB** [comment]
I also encountered this error  in orator==0.9.9
