### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'autocommit'

### ISSUE THREAD

**Issue by tuxknight** [sdispater/orator#234]
Using gunicorn as wsgi server will produce this exception after a few requests  to the same API(/user/add) than received normal response.
And every request will produce this exception  after a lot requests. 

Other APIs are working properly from beginning. Only that API always crash.

I could not figure out why self._connection became a None. But  add a reconnect action ``self._reconnect_if_missing_connection()`` in method transaction(self) whill fix it or using db.reconnect()  before  with db.transaction() .
        

```
2018-05-17 19:10:28,643 flask.app ERROR [app:1761:log_exception] Exception on /user/add [POST]
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.6.5/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/.pyenv/versions/3.6.5/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/.pyenv/versions/3.6.5/lib/python3.6/site-packages/flask_restplus/api.py", line 313, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.6.5/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/user/.pyenv/versions/3.6.5/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/data/app/user/user.py", line 49, in post
    with db.transaction():
  File "/home/user/.pyenv/versions/3.6.5/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/user/.pyenv/versions/3.6.5/lib/python3.6/site-packages/orator/connections/connection.py", line 288, in transaction
    self.begin_transaction()
  File "/home/user/.pyenv/versions/3.6.5/lib/python3.6/site-packages/orator/connections/mysql_connection.py", line 40, in begin_transaction
    self._connection.autocommit(False)
AttributeError: 'NoneType' object has no attribute 'autocommit'
2018-05-17 19:10:28,648 orator.database_manager DEBUG [database_manager:90:disconnect] Disconnecting mysql
2018-05-17 19:10:28,648 orator.database_manager DEBUG [database_manager:90:disconnect] Disconnecting mysql
2018-05-17 19:10:28,648 orator.connection DEBUG [connection:362:disconnect] MySQLConnection is disconnecting
2018-05-17 19:10:28,648 orator.connection DEBUG [connection:362:disconnect] MySQLConnection is disconnecting
2018-05-17 19:10:28,648 orator.connection DEBUG [connection:371:disconnect] MySQLConnection disconnected
2018-05-17 19:10:28,648 orator.connection DEBUG [connection:371:disconnect] MySQLConnection disconnected
```
Versions:

```
flask==0.12.0
flask-orator==0.2.0
orator==0.9.7
```

**Comment by josephmancuso** [comment]
merged PR fixing this isssue
