### ISSUE TITLE
Relationship querying does not work [Orator 0.9.7]

### ISSUE THREAD

**Issue by laith43d** [sdispater/orator#240]
I have a basic setup, 
Survey -> has_many Questions

Question -> has_many Choice
Question -> belongs_to Survey

Choice -> belongs_to Question

DB migrations and relationships are set up, as usual, however when I am trying to query relationships, I am getting the following error:

`if not isinstance(related, basestring) and issubclass(related, Model):
TypeError: issubclass() arg 1 must be a class`

Attached below the migration files and models.
![screen shot 2018-05-30 at 04 07 04](https://user-images.githubusercontent.com/868008/40693250-22bc587a-63bf-11e8-9ed0-96ac6d1a8ac8.PNG)
![screen shot 2018-05-30 at 04 07 13](https://user-images.githubusercontent.com/868008/40693251-237af294-63bf-11e8-8bf7-920fd01c4156.PNG)
![screen shot 2018-05-30 at 04 07 21](https://user-images.githubusercontent.com/868008/40693252-24e3dd44-63bf-11e8-9ec7-45b875c7a269.PNG)
![screen shot 2018-05-30 at 04 07 32](https://user-images.githubusercontent.com/868008/40693253-25266c4a-63bf-11e8-8ae5-7c3827c2c7be.PNG)
![screen shot 2018-05-30 at 04 07 38](https://user-images.githubusercontent.com/868008/40693254-2568218a-63bf-11e8-9352-eb71de4fef44.PNG)
![screen shot 2018-05-30 at 04 07 45](https://user-images.githubusercontent.com/868008/40693255-26549862-63bf-11e8-8a9c-67d5f996a1fb.PNG)
![screen shot 2018-05-30 at 04 07 52](https://user-images.githubusercontent.com/868008/40693256-267bcd9c-63bf-11e8-9b30-dbc899bdfcae.PNG)

**Comment by laith43d** [comment]
Full traceback log:

`
Traceback (most recent call last):
  File "/Users/lzah/MEGA/PycharmProjects/juju-survey/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/lzah/MEGA/PycharmProjects/juju-survey/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/lzah/MEGA/PycharmProjects/juju-survey/venv/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/lzah/MEGA/PycharmProjects/juju-survey/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/lzah/MEGA/PycharmProjects/juju-survey/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/lzah/MEGA/PycharmProjects/juju-survey/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/lzah/MEGA/PycharmProjects/juju-survey/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/lzah/MEGA/PycharmProjects/juju-survey/venv/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/lzah/MEGA/PycharmProjects/juju-survey/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/lzah/MEGA/PycharmProjects/juju-survey/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/lzah/MEGA/PycharmProjects/juju-survey/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/lzah/MEGA/PycharmProjects/juju-survey/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/lzah/MEGA/PycharmProjects/juju-survey/venv/lib/python3.6/site-packages/flask_classful.py", line 268, in proxy
    response = view(**request.view_args)
  File "/Users/lzah/MEGA/PycharmProjects/juju-survey/venv/lib/python3.6/site-packages/flask_classful.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/Users/lzah/MEGA/PycharmProjects/juju-survey/api/Survey.py", line 12, in all
    print(survey.questions.choices)
  File "/Users/lzah/MEGA/PycharmProjects/juju-survey/venv/lib/python3.6/site-packages/orator/orm/utils.py", line 184, in __get__
    relation = self._get(instance)
  File "/Users/lzah/MEGA/PycharmProjects/juju-survey/venv/lib/python3.6/site-packages/orator/orm/utils.py", line 352, in _get
    _wrapped=False
  File "/Users/lzah/MEGA/PycharmProjects/juju-survey/venv/lib/python3.6/site-packages/orator/orm/model.py", line 892, in has_many
    instance = self._get_related(related, True)
  File "/Users/lzah/MEGA/PycharmProjects/juju-survey/venv/lib/python3.6/site-packages/orator/orm/model.py", line 1177, in _get_related
    if not isinstance(related, basestring) and issubclass(related, Model):
TypeError: issubclass() arg 1 must be a class`

**Comment by josephmancuso** [comment]
what line is actually triggering the error? is it the Survey.find()? or the line inside the print statement

**Comment by josephmancuso** [comment]
I'm wondering if the relationship isn't a class then what the heck is it? 

when you do `from models import Question` what happens when you do `print(Question)` right under it?

```python
from models import Question
print(Question)
```

does that print something like `<class models.Question>` or `<module models.Question>`. I have a sneaky suspicion that it might be a module maybe? Because this works in my application find

**Comment by laith43d** [comment]
I have imported them in the __init__.py file, the results show:
`<class 'models.Survey.Survey'>`

**Comment by laith43d** [comment]
By the way, the exact same configuration works perfectly fine for SQLAlchemy!

**Comment by laith43d** [comment]
Yes, actually that helps a lot.

The problem was not with the naming of the files nor the imports, the problem was with the two-way relationship reference, as soon as I removed the backward reference with @belongs_to I got it right.

Thanks for the help @finetuned89
