### ISSUE TITLE
Installing from source on 0.9 branch

### ISSUE THREAD

**Issue by claygorman** [sdispater/orator#253]
`-e git+https://github.com/sdispater/orator.git@0.9#egg=orator` does not work due to setup.py missing. 0.8 and develop both have files 0.9 does not.

@josephmancuso I was hoping you had a solution for this? I am trying to install from source because after a day or so I get connection errors. Restarting the container fixes my issue. I will link issue below.

https://github.com/sdispater/orator/issues/233

**Comment by josephmancuso** [comment]
you're using poetry for dependency management, correct?

**Comment by claygorman** [comment]
I tried pip and pipenv. Poetry is required to install from 0.9 branch?

**Comment by josephmancuso** [comment]
I also use Pipenv but I remember an earlier version of Poetry being able to build a setup.py file if I remember correctly but I can't find it anymore .. :thinking:

**Comment by psincraian** [comment]
I have the same problem... I cannot build orator from source

```
(.venv) ~/W/test$ pip install git+https://github.com/sdispater/orator.git@0.9
Collecting git+https://github.com/sdispater/orator.git@0.9
  Cloning https://github.com/sdispater/orator.git (to revision 0.9) to /tmp/pip-req-build-lnm31sw3
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/petru/.pyenv/versions/3.6.0/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-lnm31sw3/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-lnm31sw3/
```
