### ISSUE TITLE
orator.exceptions.query.QueryException: (2013, 'Lost connection to MySQL server during query') 

### ISSUE THREAD

**Issue by Spawn** [sdispater/orator#258]
Hi all. Here is an exception:

``` "Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.6/site-packages/falcon/api.py", line 244, in __call__
    responder(req, resp, **params)
  File "/app/authentication/controllers.py", line 94, in on_get
    user = User.find_or_fail(user_id)
  File "/usr/local/lib/python3.6/site-packages/orator/orm/builder.py", line 147, in find_or_fail
    result = self.find(id, columns)
  File "/usr/local/lib/python3.6/site-packages/orator/orm/builder.py", line 107, in find
    return self.first(columns)
  File "/usr/local/lib/python3.6/site-packages/orator/orm/builder.py", line 170, in first
    return self.take(1).get(columns).first()
  File "/usr/local/lib/python3.6/site-packages/orator/orm/builder.py", line 198, in get
    models = self.get_models(columns)
  File "/usr/local/lib/python3.6/site-packages/orator/orm/builder.py", line 444, in get_models
    results = self.apply_scopes().get_query().get(columns).all()
  File "/usr/local/lib/python3.6/site-packages/orator/query/builder.py", line 1061, in get
    results = self._processor.process_select(self, self._run_select())
  File "/usr/local/lib/python3.6/site-packages/orator/query/builder.py", line 1077, in _run_select
    not self._use_write_connection
  File "/usr/local/lib/python3.6/site-packages/orator/connections/connection.py", line 34, in _run
    e, query, bindings, wrapped
  File "/usr/local/lib/python3.6/site-packages/orator/connections/connection.py", line 341, in _try_again_if_caused_by_lost_connection
    raise QueryException(query, bindings, e)
orator.exceptions.query.QueryException: (2013, 'Lost connection to MySQL server during query') (SQL: SELECT * FROM `users` WHERE `users`.`id` = %s LIMIT 1 (['285b838e07474c2bb68a756ca780f470']))```

Orator == 0.9.7 with PyMySQL==0.9.2

**Comment by Spawn** [comment]
And yes, that's because 
```    def _caused_by_lost_connection(self, e):
        message = str(e)

        for s in ['server has gone away',
                  'no connection to the server',
                  'Lost Connection',
                  'is dead or not enabled',
                  'Error while sending',
                  'decryption failed or bad record mac',
                  'server closed the connection unexpectedly',
                  'SSL connection has been closed unexpectedly',
                  'Error writing data to the connection',
                  'Resource deadlock avoided',]:
            if s in message:
                return False

        return False```
Here is strings with upper-case letters.
