### ISSUE TITLE
Paginate bug: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by psincraian** [sdispater/orator#262]
Hi there,

I have a problem paginating queries that uses a where and an order_by_raw expression. For example the following query does not work:
```python
db = DatabaseManager(CONFIG)
data = db.table("products") \
            .where('id', 1) \
            .order_by_raw("location <-> point(%s, %s)", (60.0, 50.0)) \
            .paginate(60, 1)
``` 

The traceback is the following:
```
Traceback (most recent call last):
  File "main.py", line 18, in <module>
    .paginate(60, 1)
  File "/home/petru/Workspace/orator/orator/query/builder.py", line 1101, in paginate
    total = self.get_count_for_pagination()
  File "/home/petru/Workspace/orator/orator/query/builder.py", line 1135, in get_count_for_pagination
    total = self.count()
  File "/home/petru/Workspace/orator/orator/query/builder.py", line 1270, in count
    return int(self.aggregate('count', *columns))
  File "/home/petru/Workspace/orator/orator/query/builder.py", line 1347, in aggregate
    results = self.get(*columns).all()
  File "/home/petru/Workspace/orator/orator/query/builder.py", line 1061, in get
    results = self._processor.process_select(self, self._run_select())
  File "/home/petru/Workspace/orator/orator/query/builder.py", line 1077, in _run_select
    not self._use_write_connection
  File "/home/petru/Workspace/orator/orator/connections/connection.py", line 34, in _run
    e, query, bindings, wrapped
  File "/home/petru/Workspace/orator/orator/connections/connection.py", line 341, in _try_again_if_caused_by_lost_connection
    raise QueryException(query, bindings, e)
orator.exceptions.query.QueryException: not all arguments converted during string formatting (SQL: SELECT COUNT(*) AS aggregate FROM "products_search" WHERE "id" = %s ([1, 60.0, 50.0]))
```

The problem is that the bindings from the order function are not removed and the python interpreter crashes.

**Comment by psincraian** [comment]
I would like to do a PR to solve this issue, I took a look at the code and a possible solution would be to backup the bindings, something like:

```python
def _backup_fields_for_count(self): 
    for field, binding in [('orders', 'order'), ('limit', None), ('offset', None)]: 
        self._backups[field] = {} 
        self._backups[field]["query"] = getattr(self, field) 
        if binding is not None: 
            self._backups[field]["binding"] = self.get_raw_bindings()[binding] 
            self.set_bindings([], binding) 
 
        setattr(self, field, None) 
 
def _restore_fields_for_count(self): 
    for field, binding in [('orders', 'order'), ('limit', None), ('offset', None)]: 
        setattr(self, field, self._backups[field]["query"]) 
        if binding is not None: 
            self.add_binding(self._backups[field]["binding"], binding)
```

Maybe there is a better approach to solve this issue, I would like you to guide me a little to solve it well :blush: 

Finally, I would like to say that I love the project.
