### ISSUE TITLE
MySQL Read - Write config problem

### ISSUE THREAD

**Issue by msyagli** [sdispater/orator#266]
I am using autossh tunneling between DB servers and application servers. Connection works without read/write options. But when I use read/write options in the config, it generates the following error. Is there anyone can guide me? Thanks.

My config example:  
```
config = {
    'mysql': {
        'read': {
            'username': 'user1',
            'password': 'password1',
            'port': 33060
        },
        'write': {
            'username': 'user2',
            'password': 'password2',
            'port': 33080
        },
        'driver': 'mysql',
        'host': '127.0.0.1',
        'database': 'dbname',
        'prefix': ''
    }
}

db = DatabaseManager(config)
Model.set_connection_resolver(db)
```
Here it is the error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.6/dist-packages/falcon/api.py", line 244, in __call__
    responder(req, resp, **params)
  File "/home/app/api.py", line 335, in on_get
    component = db.table('components') \
  File "/usr/local/lib/python3.6/dist-packages/orator/database_manager.py", line 181, in __getattr__
    return getattr(self.connection(), item)
  File "/usr/local/lib/python3.6/dist-packages/orator/database_manager.py", line 43, in connection
    connection = self._make_connection(name)
  File "/usr/local/lib/python3.6/dist-packages/orator/database_manager.py", line 132, in _make_connection
    return self._factory.make(config, name)
  File "/usr/local/lib/python3.6/dist-packages/orator/connectors/connection_factory.py", line 34, in make
    return self._create_read_write_connection(config)
  File "/usr/local/lib/python3.6/dist-packages/orator/connectors/connection_factory.py", line 50, in _create_read_write_connection
    connection = self._create_single_connection(self._get_write_config(config))
  File "/usr/local/lib/python3.6/dist-packages/orator/connectors/connection_factory.py", line 67, in _get_write_config
    write_config = self._get_read_write_config(config, 'write')
  File "/usr/local/lib/python3.6/dist-packages/orator/connectors/connection_factory.py", line 73, in _get_read_write_config
    return random.choice(config[type])
  File "/usr/lib/python3.6/random.py", line 261, in choice
    return seq[i]
```

**Comment by josephmancuso** [comment]
What is the exception? I only see a stack trace there

**Comment by msyagli** [comment]
> What is the exception? I only see a stack trace there

Ahh sorry, my bad.

`
Exception(most recent call last)

AttributeError: type object 'Video' has no attribute 'where'
  File "orator/orm/model.py", line 57, in __getattr__
    return type.__getattribute__(cls, item)

AttributeError: type object 'Model' has no attribute 'boot_model'
  File "orator/orm/model.py", line 57, in __getattr__
    return type.__getattribute__(cls, item)
`

**Comment by luoxiaohei** [comment]
@josephmancuso document for [read-write-connections](https://orator-orm.com/docs/0.9/basic_usage.html#read-write-connections) is wrong.

The `_get_read_write_config` function use `random.choice` to choice a config, it can't working with dict.

https://github.com/sdispater/orator/blob/bd90bf198ee897751848f9a92e49d18e60a74136/orator/connectors/connection_factory.py#L63-L65

The correct configuration is

```python
config = {
    'mysql': {
        'read': [{
            'host': '192.168.1.1'
        }],
        'write': [{
            'host': '192.168.1.2'
        }],
        'driver': 'mysql',
        'database': 'database',
        'username': 'root',
        'password': '',
        'prefix': ''
    }
}
```

**Comment by mouday** [comment]
document is error ,
https://orator-orm.com/docs/0.9/basic_usage.html#read-write-connections
