### ISSUE TITLE
SQL Subquery

### ISSUE THREAD

**Issue by lighth7015** [sdispater/orator#275]
Good evening,

I am trying to get a sub-query working, however I'm not quite sure how.

```python
subquery = db.table( "account_ledger" ) \
			.where_raw( db.raw( "accounts.id = account_ledger.account_id" )) \
			.order_by( "account_ledger.created_at" ) \
			.latest() \
			.limit( 1 ) \

collection = db.table( "accounts" ) \
			.select_sub( subquery, "payment" ) \
			.group_by( "accounts.id" ) \
			.where_raw( "\"payment\".\"successful\"" ) \
			.get()
```

yields me the following error:
```
Traceback (most recent call last):
  File "/home/robert_/pyx/marble/env/bin/marble", line 11, in <module>
    load_entry_point('marble', 'console_scripts', 'marble')()
  File "/home/robert_/pyx/marble/env/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/robert_/pyx/marble/env/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/robert_/pyx/marble/env/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/robert_/pyx/marble/env/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/robert_/pyx/marble/env/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/robert_/pyx/marble/env/lib/python3.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/robert_/pyx/marble/env/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/robert_/pyx/marble/marble/app/Start.py", line 84, in start
    .select_sub( subquery, "payment" ) \
  File "/home/robert_/pyx/marble/env/lib/python3.7/site-packages/orator/query/builder.py", line 123, in select_sub
    query = query.to_sql()
  File "/home/robert_/pyx/marble/env/lib/python3.7/site-packages/orator/query/builder.py", line 988, in to_sql
    return self._grammar.compile_select(self)
  File "/home/robert_/pyx/marble/env/lib/python3.7/site-packages/orator/query/grammars/grammar.py", line 30, in compile_select
    return self._concatenate(self._compile_components(query)).strip()
  File "/home/robert_/pyx/marble/env/lib/python3.7/site-packages/orator/query/grammars/grammar.py", line 43, in _compile_components
    sql[component] = getattr(self, method)(query, component_value)
  File "/home/robert_/pyx/marble/env/lib/python3.7/site-packages/orator/query/grammars/grammar.py", line 133, in _compile_wheres
    getattr(self, method)(query, where)))
  File "/home/robert_/pyx/marble/env/lib/python3.7/site-packages/orator/query/grammars/grammar.py", line 231, in _where_raw
    re.I)
  File "/home/robert_/pyx/marble/env/lib/python3.7/re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
```

Why would this be happening?
Thank you!

**Comment by lighth7015** [comment]
What would that look like with relationships?

**Comment by lighth7015** [comment]
I'm looking to retrieve a list of accounts whos' most recent ledger (account_ledger) is successful (account_ledger.successful)
