### ISSUE TITLE
TypeError: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by fangzheng0518** [sdispater/orator#284]
I used orator 0.9.8 and Python version 3.7
When I try to insert data, I get the following exception

#### python code
```python
from orator import DatabaseManager

config = {
    'mysql': {
        'driver': 'mysql',
        'host': 'localhost',
        'database': 'test',
        'user': 'root',
        'password': '123',
        'prefix': '',
        'log_queries': True
    }
}

db = DatabaseManager(config)

db.insert('insert into user (username,password,email) values (?,?,?)', ['John','John','John@qq.com'])
```
#### exception info
```
Traceback (most recent call last):
  File "/Users/fangzheng/Library/Python/3.7/lib/python/site-packages/orator/connections/connection.py", line 31, in _run
    result = wrapped(self, query, bindings, *args, **kwargs)
  File "/Users/fangzheng/Library/Python/3.7/lib/python/site-packages/orator/connections/connection.py", line 251, in statement
    return self._new_cursor().execute(query, bindings)
  File "/Users/fangzheng/Library/Python/3.7/lib/python/site-packages/pymysql/cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "/Users/fangzheng/Library/Python/3.7/lib/python/site-packages/pymysql/cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
TypeError: not all arguments converted during string formatting

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/fangzheng/PycharmProjects/pydemo/ORM/orator/test.py", line 39, in <module>
    db.insert('insert into user (username,password,email) values (?,?,?)', ['John','John','John@qq.com'])
  File "/Users/fangzheng/Library/Python/3.7/lib/python/site-packages/orator/connections/connection.py", line 236, in insert
    return self.statement(query, bindings)
  File "/Users/fangzheng/Library/Python/3.7/lib/python/site-packages/orator/connections/connection.py", line 34, in _run
    e, query, bindings, wrapped
  File "/Users/fangzheng/Library/Python/3.7/lib/python/site-packages/orator/connections/connection.py", line 341, in _try_again_if_caused_by_lost_connection
    raise QueryException(query, bindings, e)
orator.exceptions.query.QueryException: not all arguments converted during string formatting (SQL: insert into user (username,password,email) values (?,?,?) (['John', 'John', 'John@qq.com']))

Process finished with exit code 1

```

**Comment by psincraian** [comment]
You only need to specify the table and the arguments: https://orator-orm.com/docs/0.9/query_builder.html#inserts

```python
# With keywords arguments
db.table('users').insert(email='foo@bar.com', votes=0)

# Or with dictionary
db.table('users').insert({
    'email': 'foo@bar.com',
    'votes': 0
})
```
