### ISSUE TITLE
It often raises an QueryException

### ISSUE THREAD

**Issue by gamelife1314** [sdispater/orator#316]
- Tornado 6.0.3
- uvloop
- graphene 2.1.6
- orator 0.9.8
- python 3.7.3
- pymysql 0.9.3

```
ERROR:tornado.application:Uncaught exception POST /ehs (::1)
HTTPServerRequest(protocol='http', host='localhost:5000', method='POST', uri='/ehs', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Users/fudenglong/.local/share/virtualenvs/ehs-api-MZQiJUEh/lib/python3.7/site-packages/orator/connections/connection.py", line 31, in _run
    result = wrapped(self, query, bindings, *args, **kwargs)
  File "/Users/fudenglong/.local/share/virtualenvs/ehs-api-MZQiJUEh/lib/python3.7/site-packages/orator/connections/connection.py", line 199, in select
    cursor.execute(query, bindings)
  File "/Users/fudenglong/.local/share/virtualenvs/ehs-api-MZQiJUEh/lib/python3.7/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/Users/fudenglong/.local/share/virtualenvs/ehs-api-MZQiJUEh/lib/python3.7/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/Users/fudenglong/.local/share/virtualenvs/ehs-api-MZQiJUEh/lib/python3.7/site-packages/pymysql/connections.py", line 516, in query
    self._execute_command(COMMAND.COM_QUERY, sql)
  File "/Users/fudenglong/.local/share/virtualenvs/ehs-api-MZQiJUEh/lib/python3.7/site-packages/pymysql/connections.py", line 750, in _execute_command
    raise err.InterfaceError("(0, '')")
pymysql.err.InterfaceError: (0, '')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/fudenglong/.local/share/virtualenvs/ehs-api-MZQiJUEh/lib/python3.7/site-packages/tornado/web.py", line 1678, in _execute
    result = await result
  File "/Users/fudenglong/workdir/python/ehs-api/application/graphql/handler.py", line 82, in prepare
    employee = await future
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/fudenglong/workdir/python/ehs-api/application/graphql/handler.py", line 79, in fn
    return Employee.get_employee_from_token(token)
  File "/Users/fudenglong/workdir/python/ehs-api/database/models/employee.py", line 49, in get_employee_from_token
    return cls.where("uid", token).first()
  File "/Users/fudenglong/.local/share/virtualenvs/ehs-api-MZQiJUEh/lib/python3.7/site-packages/orator/orm/builder.py", line 170, in first
    return self.take(1).get(columns).first()
  File "/Users/fudenglong/.local/share/virtualenvs/ehs-api-MZQiJUEh/lib/python3.7/site-packages/orator/orm/builder.py", line 198, in get
    models = self.get_models(columns)
  File "/Users/fudenglong/.local/share/virtualenvs/ehs-api-MZQiJUEh/lib/python3.7/site-packages/orator/orm/builder.py", line 444, in get_models
    results = self.apply_scopes().get_query().get(columns).all()
  File "/Users/fudenglong/.local/share/virtualenvs/ehs-api-MZQiJUEh/lib/python3.7/site-packages/orator/query/builder.py", line 1061, in get
    results = self._processor.process_select(self, self._run_select())
  File "/Users/fudenglong/.local/share/virtualenvs/ehs-api-MZQiJUEh/lib/python3.7/site-packages/orator/query/builder.py", line 1077, in _run_select
    not self._use_write_connection
  File "/Users/fudenglong/.local/share/virtualenvs/ehs-api-MZQiJUEh/lib/python3.7/site-packages/orator/connections/connection.py", line 34, in _run
    e, query, bindings, wrapped
  File "/Users/fudenglong/.local/share/virtualenvs/ehs-api-MZQiJUEh/lib/python3.7/site-packages/orator/connections/connection.py", line 341, in _try_again_if_caused_by_lost_connection
    raise QueryException(query, bindings, e)
orator.exceptions.query.QueryException: (0, '') (SQL: SELECT * FROM `employee` WHERE (`uid` = %s) AND (`employee`.`deleted_at` IS NULL) LIMIT 1 (['b025ff12cacd05846ec9f4a6d66a92ac']))
ERROR:tornado.access:500 POST /ehs (::1) 2.81ms

```

**Comment by gamelife1314** [comment]
@sdispater please give me a hand
