### ISSUE TITLE
TypeError: Object of type date is not JSON serializable

### ISSUE THREAD

**Issue by yxhsea** [sdispater/orator#318]
### Description

The type date is not JSON serializable

### Example

create table sql:

```
create table user(
  id int not null,
  username varchar(10) null,
  login_date date null,
  constraint user_pk
  primary key (id)
);
```

case:
```
User.find(1).to_json()
```

error:
```
Traceback (most recent call last):
  File "/Users/yxhsea/pywork/hipy/main.py", line 39, in <module>
    print(json.dumps(res))
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type date is not JSON serializable
```

**Comment by josephmancuso** [comment]
You will have to specify the `__dates__ = ['login_date']`  on your model.
