### ISSUE TITLE
Error when running commands

### ISSUE THREAD

**Issue by kevin-klein** [sdispater/orator#352]
When i try `$ orator make:migration create_users_table`

I get this error:
```
Traceback (most recent call last):
  File "/mnt/f/work/project/env/bin/orator", line 7, in <module>
    from orator.commands.application import application
  File "/mnt/f/work/project/env/lib/python3.6/site-packages/orator/commands/application.py", line 9, in <module>      from .migrations import (
  File "/mnt/f/work/project/env/lib/python3.6/site-packages/orator/commands/migrations/__init__.py", line 3, in <module>
    from .install_command import InstallCommand
  File "/mnt/f/work/project/env/lib/python3.6/site-packages/orator/commands/migrations/install_command.py", line 4, in <module>
    from .base_command import BaseCommand
  File "/mnt/f/work/project/env/lib/python3.6/site-packages/orator/commands/migrations/base_command.py", line 5, in <module>
    from ..command import Command
  File "/mnt/f/work/project/env/lib/python3.6/site-packages/orator/commands/command.py", line 4, in <module>
from cleo import Command as BaseCommand, InputOption, ListInput
ImportError: cannot import name 'InputOption'
```

**Comment by wie-niet** [comment]
try updating your orator package:
`pip install --upgrade orator`

I had the same issue, apparently the installed "cleo" package was outdated. After re-installing orator all worked fine.

**Comment by EpocDotFr** [comment]
Had the same issue on Python 3.6, turned out that I had to update PIP so dependencies are properly computed: `python -m pip install --upgrade pip`
