### ISSUE TITLE
Auto-generated index names are sometimes too long

### ISSUE THREAD

**Issue by joelbarker2011** [sdispater/orator#52]
[MySQL identifiers have a maximum length of 64 characters.](https://dev.mysql.com/doc/refman/5.7/en/identifiers.html) [Postgres identifiers appear to have a max length of 63 characters.](http://www.postgresql.org/docs/9.5/static/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS) However, `orator` auto-generates index names (primary key, unique, and index) without ensuring that they are <= 63/64 characters long.

Test case:
```python
# test.py
from os import environ as env

from orator import DatabaseManager
from orator import Model
from orator import Schema

if __name__ == '__main__':
    config = {
        'mytestdb': {
            'driver': 'mysql',
            'user': env['DB_USER'],
            'password': env['DB_PASS'],
            'host': env.get('DB_HOST', 'localhost'),
            'database': env['DB_NAME']
        }
    }

    db = DatabaseManager(config)
    Model.set_connection_resolver(db)
    schema = Schema(db)

    schema.drop_if_exists('widgets')

    with schema.create('widgets') as t:
        t.increments('id')
        t.integer('field_with_really_long_name')
        t.integer('another_field_with_long_name')
        t.unique(['field_with_really_long_name', 'another_field_with_long_name'])

# run with:
# DB_USER=mydbuser DB_PASS=mydbpass DB_NAME=mydatabase python test.py
```

Current result of running this script:
```
Traceback (most recent call last):
  File "test.py", line 29, in <module>
    t.unique(['field_with_really_long_name', 'another_field_with_long_name'])
  File "/home/joel/anaconda2/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/home/joel/anaconda2/lib/python2.7/site-packages/orator/schema/builder.py", line 100, in create
    self._build(blueprint)
  File "/home/joel/anaconda2/lib/python2.7/site-packages/orator/schema/builder.py", line 147, in _build
    blueprint.build(self._connection, self._grammar)
  File "/home/joel/anaconda2/lib/python2.7/site-packages/orator/schema/blueprint.py", line 31, in build
    connection.statement(statement)
  File "/home/joel/anaconda2/lib/python2.7/site-packages/orator/connections/connection.py", line 34, in _run
    e, query, bindings, wrapped
  File "/home/joel/anaconda2/lib/python2.7/site-packages/orator/connections/connection.py", line 318, in _try_again_if_caused_by_lost_connection
    raise QueryException(query, bindings, e)
orator.exceptions.query.QueryException: (1059, "Identifier name 'widgets_field_with_really_long_name_another_field_with_long_name_unique' is too long") (SQL: ALTER TABLE `widgets` ADD UNIQUE widgets_field_with_really_long_name_another_field_with_long_name_unique(`field_with_really_long_name`, `another_field_with_long_name`) (None))
```

A possible fix would be cutting off the end of the long name, and suffixing a hash to avoid name collisions, in _orator/schema/blueprint.py_:
```diff
    def _create_index_name(self, type, columns):
        if not isinstance(columns, list):
            columns = [columns]

        index = '%s_%s_%s' % (self._table, '_'.join(columns), type)

-       return index.lower().replace('-', '_').replace('.', '_')
+       index = index.lower().replace('-', '_').replace('.', '_')
+
+       # keep name to 63 chars to avoid identifiers that are too long
+       if len(index) > 63:
+           index = index[:47] + '_' + hex(hash(index))[-7:]
+
+       return index
```
I've only tested this with MySQL (MariaDB 10.1).

**Comment by joelbarker2011** [comment]
Although this is nowhere mentioned in the docs, the `primary()`, `unique()`, and `index()` methods (which create indexes) all accept an additional parameter, `name`:

```python
     with schema.create('widgets') as t:
        t.increments('id')
        t.integer('field_with_really_long_name')
        t.integer('another_field_with_long_name')
        t.unique(['field_with_really_long_name', 'another_field_with_long_name'], name='my_uniq_idx')
```

**Comment by sdispater** [comment]
This is the best solution for now.

I will add a note in the documentation.

**Comment by sdispater** [comment]
The documentation has been updated: https://orator-orm.com/docs/0.8/schema_builder.html#adding-indexes
