### ISSUE TITLE
Composite primary keys do not work

### ISSUE THREAD

**Issue by joelbarker2011** [sdispater/orator#54]
It is possible to create a new model (with `schema.create`) that uses a composite primary key (with `table.primary(['column1', 'column2'])`). Unfortunately, it does not appear that it is possible to create a `Model` subclass that uses this composite key.

Specifying the composite key in the `Model` subclass with `__primary_key__ = ('column1', 'column2')` (using a **tuple**) results in this error:
```
Traceback (most recent call last):
  File "test.py", line 39, in <module>
    print w.serialize()
  File "/home/joel/anaconda2/lib/python2.7/site-packages/orator/orm/model.py", line 2146, in serialize
    attributes = self.attributes_to_dict()
  File "/home/joel/anaconda2/lib/python2.7/site-packages/orator/orm/model.py", line 2168, in attributes_to_dict
    attributes = self._get_dictable_attributes()
  File "/home/joel/anaconda2/lib/python2.7/site-packages/orator/orm/model.py", line 2207, in _get_dictable_attributes
    return self._get_dictable_items(self._attributes)
  File "/home/joel/anaconda2/lib/python2.7/site-packages/orator/orm/model.py", line 2261, in _get_dictable_items
    return {x: values[x] for x in values.keys() if x not in self.__hidden__ and not x.startswith('_')}
  File "/home/joel/anaconda2/lib/python2.7/site-packages/orator/orm/model.py", line 2261, in <dictcomp>
    return {x: values[x] for x in values.keys() if x not in self.__hidden__ and not x.startswith('_')}
AttributeError: 'tuple' object has no attribute 'startswith'
```

Specifying the composite key in the `Model` subclass with `__primary_key__ = ['column1', 'column2']` (using a **list**) results in this error:
```
Traceback (most recent call last):
  File "test.py", line 38, in <module>
    w = Widget.create(column1=col1, column2=col2)
  File "/home/joel/anaconda2/lib/python2.7/site-packages/orator/orm/model.py", line 412, in create
    model.save()
  File "/home/joel/anaconda2/lib/python2.7/site-packages/orator/orm/model.py", line 1513, in save
    saved = self._perform_insert(query, options)
  File "/home/joel/anaconda2/lib/python2.7/site-packages/orator/orm/model.py", line 1584, in _perform_insert
    self._insert_and_set_id(query, attributes)
  File "/home/joel/anaconda2/lib/python2.7/site-packages/orator/orm/model.py", line 1608, in _insert_and_set_id
    self.set_attribute(key_name, id)
  File "/home/joel/anaconda2/lib/python2.7/site-packages/orator/orm/model.py", line 2507, in set_attribute
    if self._has_set_mutator(key):
  File "/home/joel/anaconda2/lib/python2.7/site-packages/orator/orm/model.py", line 2378, in _has_set_mutator
    if key not in self._mutator_cache[klass]:
TypeError: unhashable type: 'list'
```

This is using the PyMySQL database adapter.

**Comment by joelbarker2011** [comment]
Test script:
```python
# test.py
from os import environ as env

from orator import DatabaseManager
from orator import Model
from orator import Schema

if __name__ == '__main__':
    config = {
        'mytestdb': {
            'driver': 'mysql',
            'user': env['DB_USER'],
            'password': env['DB_PASS'],
            'host': env.get('DB_HOST', 'localhost'),
            'database': env['DB_NAME']
        }
    }

    db = DatabaseManager(config)
    Model.set_connection_resolver(db)
    schema = Schema(db)

    schema.drop_if_exists('widgets')

    with schema.create('widgets') as table:
        table.integer('column1')
        table.integer('column2')
        table.primary(['column1', 'column2'])

    class Widget(Model):
        __guarded__ = []
        __timestamps__ = False
        __primary_key__ = ['column1', 'column2']
        pass

    col1 = id(__name__) % 1000;
    col2 = id(__name__) % 1001;
    w = Widget.create(column1=col1, column2=col2)
    print w.serialize()

# run with:
# DB_USER=mydbuser DB_PASS=mydbpass DB_NAME=mydatabase python test.py
```

**Comment by sdispater** [comment]
As of right now, it is not supported in Orator models and I don't plan to add it in a near future.

If this is critical for you you can use the query builder directly.

**Comment by rohalla2** [comment]
@sdispater Is there any chance this is in the pipeline to be implemented?

**Comment by gilvan-reis-meliuz** [comment]
@sdispater at least a comment in the docs should be added, because I wasted a lot of time trying make this feature work.

I created a id field (only to pass) and use the composite key with the unique

**Comment by josephmancuso** [comment]
https://github.com/orator-orm/docs
