### ISSUE TITLE
Keys_fix not defined

### ISSUE THREAD

**Issue by james-hoegerl** [sdispater/orator#55]
When I run your start up tutorial I get.

`Traceback (most recent call last):
  File "test.py", line 19, in <module> print(User.all())
  File "/Library/Python/2.7/site-packages/orator/orm/model.py", line 544, in all
    instance = cls()
  File "/Library/Python/2.7/site-packages/orator/orm/model.py", line 121, in __init__
    self._boot_if_not_booted()
  File "/Library/Python/2.7/site-packages/orator/orm/model.py", line 148, in _boot_if_not_booted
    klass._boot()
  File "/Library/Python/2.7/site-packages/orator/orm/model.py", line 167, in _boot
    cls._boot_columns()
  File "/Library/Python/2.7/site-packages/orator/orm/model.py", line 171, in _boot_columns
    connection = cls.resolve_connection()
  File "/Library/Python/2.7/site-packages/orator/orm/model.py", line 2758, in resolve_connection
    return cls.__resolver.connection(connection)
  File "/Library/Python/2.7/site-packages/orator/database_manager.py", line 43, in connection
    connection = self._make_connection(name)
  File "/Library/Python/2.7/site-packages/orator/database_manager.py", line 129, in _make_connection
    return self._factory.make(config, name)
  File "/Library/Python/2.7/site-packages/orator/connectors/connection_factory.py", line 36, in make
    return self._create_single_connection(config)
  File "/Library/Python/2.7/site-packages/orator/connectors/connection_factory.py", line 39, in _create_single_connection
    conn = self.create_connector(config).connect(config)
  File "/Library/Python/2.7/site-packages/orator/connectors/mysql_connector.py", line 31, in connect
    for key, value in keys_fix.items():
NameError: global name 'keys_fix' is not defined`

Seems like I'm following it correctly. Sorry if this is more tech support than an issue but I couldn't find any similar errors online elsewhere.

**Comment by sdispater** [comment]
This error shoud only occur when you do not have a package for MySQL installed (either `mysqlclient` or `pymysql`). Try installing one one them.

**Comment by james-hoegerl** [comment]
My apologies it said so right in the getting started docs.

I'm getting this now.

`
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    users = Pitchlist.all()
  File "/usr/local/lib/python2.7/dist-packages/orator/orm/model.py", line 544, in all
    instance = cls()
  File "/usr/local/lib/python2.7/dist-packages/orator/orm/model.py", line 121, in __init__
    self._boot_if_not_booted()
  File "/usr/local/lib/python2.7/dist-packages/orator/orm/model.py", line 148, in _boot_if_not_booted
    klass._boot()
  File "/usr/local/lib/python2.7/dist-packages/orator/orm/model.py", line 167, in _boot
    cls._boot_columns()
  File "/usr/local/lib/python2.7/dist-packages/orator/orm/model.py", line 172, in _boot_columns
    columns = connection.get_schema_manager().list_table_columns(cls.__table__ or inflection.tableize(cls.__name__))
  File "/usr/local/lib/python2.7/dist-packages/orator/connections/mysql_connection.py", line 37, in get_schema_manager
    return MySQLSchemaManager(self)
  File "/usr/local/lib/python2.7/dist-packages/orator/dbal/schema_manager.py", line 22, in __init__
    self._platform = self._connection.get_database_platform()
  File "/usr/local/lib/python2.7/dist-packages/orator/connections/connection.py", line 124, in get_database_platform
    server_version = self.server_version
  File "/usr/local/lib/python2.7/dist-packages/orator/connections/connection.py", line 508, in server_version
    self._server_version = self.get_server_version()
  File "/usr/local/lib/python2.7/dist-packages/orator/connections/mysql_connection.py", line 70, in get_server_version
    tuple_version = self._connection._server_version
AttributeError: 'Connection' object has no attribute '_server_version'
`

**Comment by sdispater** [comment]
Yes, it's a known problem fixed in #39 .

The fix will be included in the 0.8.1 version planned for this week.

For the time being you can use the develop branch.

**Comment by james-hoegerl** [comment]
Thanks so much for the help.

**Comment by james-hoegerl** [comment]
Getting this error on dev branch

`Traceback (most recent call last):
  File "lambda.py", line 21, in <module>
    users = Pitchlist.all()
  File "/home/vagrant/Code/Lamdba/deployment/orator/orm/model.py", line 544, in all
    instance = cls()
  File "/home/vagrant/Code/Lamdba/deployment/orator/orm/model.py", line 121, in __init__
    self._boot_if_not_booted()
  File "/home/vagrant/Code/Lamdba/deployment/orator/orm/model.py", line 148, in _boot_if_not_booted
    klass._boot()
  File "/home/vagrant/Code/Lamdba/deployment/orator/orm/model.py", line 167, in _boot
    cls._boot_columns()
  File "/home/vagrant/Code/Lamdba/deployment/orator/orm/model.py", line 171, in _boot_columns
    connection = cls.resolve_connection()
  File "/home/vagrant/Code/Lamdba/deployment/orator/orm/model.py", line 2758, in resolve_connection
    return cls.__resolver.connection(connection)
  File "/home/vagrant/Code/Lamdba/deployment/orator/database_manager.py", line 43, in connection
    connection = self._make_connection(name)
  File "/home/vagrant/Code/Lamdba/deployment/orator/database_manager.py", line 129, in _make_connection
    return self._factory.make(config, name)
  File "/home/vagrant/Code/Lamdba/deployment/orator/connectors/connection_factory.py", line 36, in make
    return self._create_single_connection(config)
  File "/home/vagrant/Code/Lamdba/deployment/orator/connectors/connection_factory.py", line 39, in _create_single_connection
    conn = self.create_connector(config).connect(config)
  File "/home/vagrant/Code/Lamdba/deployment/orator/connectors/mysql_connector.py", line 38, in connect
    return self.get_api().connect(**self.get_config(config))
  File "/usr/lib/python2.7/dist-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 187, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
TypeError: 'autocommit' is an invalid keyword argument for this function`

**Comment by sdispater** [comment]
Which mysql package are you using because I can't seem to be able to reproduce the problem?

**Comment by james-hoegerl** [comment]
Using pymysql. Seems to be a problem on my local machine. Working in a deployment package for aws lambda. Thanks for all your help I'll keep tinkering.

**Comment by james-hoegerl** [comment]
Connecting and querying one table just fine. Went to query another and got this. Any idea @sdispater ?

Traceback (most recent call last):
  File "/var/task/lambda.py", line 32, in createPitchZip
    song = Song.first()
  File "/var/task/orator/orm/model.py", line 58, in __getattr__
    query = cls.query()
  File "/var/task/orator/orm/model.py", line 1793, in query
    return cls().new_query()
  File "/var/task/orator/orm/model.py", line 121, in __init__
    self._boot_if_not_booted()
  File "/var/task/orator/orm/model.py", line 148, in _boot_if_not_booted
    klass._boot()
  File "/var/task/orator/orm/model.py", line 167, in _boot
    cls._boot_columns()
  File "/var/task/orator/orm/model.py", line 172, in _boot_columns
    columns = connection.get_schema_manager().list_table_columns(cls.__table__ or inflection.tableize(cls.__name__))
  File "/var/task/orator/dbal/schema_manager.py", line 33, in list_table_columns
    return self._get_portable_table_columns_list(table, table_columns)
  File "/var/task/orator/dbal/schema_manager.py", line 66, in _get_portable_table_columns_list
    column = self._get_portable_table_column_definition(table_column)
  File "/var/task/orator/dbal/mysql_schema_manager.py", line 35, in _get_portable_table_column_definition
    type = self._platform.get_type_mapping(db_type)
  File "/var/task/orator/dbal/platforms/platform.py", line 359, in get_type_mapping
    return self.INTERNAL_TYPE_MAPPING[db_type]
KeyError: u'enum'

**Comment by sdispater** [comment]
It's a known issue (see #40).

It will be fixed in the next release.

**Comment by james-hoegerl** [comment]
Great. Thanks for the help @sdispater !

**Comment by tcwalther** [comment]
I just ran into the same issue. Seems like it only picks up `pymysql` - not `mysqlclient`, `MySQL-Python`, or `mysql-client-python`. Using Anaconda on Python 2.7, Orator 0.8.1

**Comment by sdispater** [comment]
I will add a check to the `Connector` class to raise an exception if mandatory packages are missing.
