### ISSUE TITLE
Raise an exception other than AttributeError when psycopg2 is unavailable

### ISSUE THREAD

**Issue by scorphus** [sdispater/orator#71]
When trying to run another project I got this:

```
Traceback (most recent call last):
  ...
  File "/.../lib/python2.7/site-packages/orator/database_manager.py", line 178, in __getattr__
    return getattr(self.connection(), item)
  File "/.../lib/python2.7/site-packages/orator/database_manager.py", line 43, in connection
    connection = self._make_connection(name)
  File "/.../lib/python2.7/site-packages/orator/database_manager.py", line 129, in _make_connection
    return self._factory.make(config, name)
  File "/.../lib/python2.7/site-packages/orator/connectors/connection_factory.py", line 36, in make
    return self._create_single_connection(config)
  File "/.../lib/python2.7/site-packages/orator/connectors/connection_factory.py", line 39, in _create_single_connection
    conn = self.create_connector(config).connect(config)
  File "/.../lib/python2.7/site-packages/orator/connectors/postgres_connector.py", line 22, in connect
    connection = self.get_api().connect(
AttributeError: 'NoneType' object has no attribute 'connect'
```
I had to open orator's source code (`/orator/connectors/postgres_connector.py`) to understand I had to install psycopg2 with pip.

**Comment by sdispater** [comment]
This issue has been fixed on the `develop` branch (commit a349906c14bf7cb25ed216db9604d8119711d498) but never made it to the `0.8` branch.

I will release the `0.8.2` version this week and this fix will be included.

**Comment by scorphus** [comment]
Great! Glad to know. As soon as it's released I close this issue. Thank you!

**Comment by sdispater** [comment]
Version `0.8.2` has just been released with the fix included.

**Comment by scorphus** [comment]
YAY! Thank you! 🎉
