### ISSUE TITLE
TypeError raised when using model's .save() method (Python 3.5)

### ISSUE THREAD

**Issue by joaobarbosa** [sdispater/orator#76]
I'm having the following problem when trying to save a model.

First, my set up:

- Python 3.5.0+
- Orator 0.8.1
- PyMySQL 0.7.4

**Note:** everything seems to be working fine using Python 2.7, it only happens with Python 3.5

Here's my model:

```python
"""Team model."""
from orator import (Model, SoftDeletes)
from orator.orm import has_many


class Team(SoftDeletes, Model):
    __timestamps__ = True
    __dates__ = ['deleted_at']
    __fillable__ = ['external_id']

    @has_many
    def logs(self):
        """Relation with log table."""
        from team_log import TeamLog
        return TeamLog
```

How it happens:

```python
team = Team.first_or_new(external_id=1)
# team.foo = 'bar';
team.save()
```

It generates the following exception + traceback:

**TypeError: cannot serialize '_io.BufferedReader' object**

```
Traceback (most recent call last):
  File "/home/user/python-projects/scout/scout_app/cli_app.py", line 24, in update_teams
    team.save()
  File "/home/user/.virtualenvs/scout/lib/python3.5/site-packages/orator/orm/model.py", line 1512, in save
    saved = self._perform_insert(query, options)
  File "/home/user/.virtualenvs/scout/lib/python3.5/site-packages/orator/orm/model.py", line 1583, in _perform_insert
    self._insert_and_set_id(query, attributes)
  File "/home/user/.virtualenvs/scout/lib/python3.5/site-packages/orator/orm/model.py", line 1605, in _insert_and_set_id
    id = query.insert_get_id(attributes, key_name)
  File "/home/user/.virtualenvs/scout/lib/python3.5/site-packages/orator/orm/builder.py", line 1168, in __getattr__
    return self.__dynamic(item)
  File "/home/user/.virtualenvs/scout/lib/python3.5/site-packages/orator/orm/builder.py", line 1145, in __dynamic
    attribute = getattr(self.apply_scopes().get_query(), method)
  File "/home/user/.virtualenvs/scout/lib/python3.5/site-packages/orator/orm/builder.py", line 936, in apply_scopes
    builder = copy.copy(self)
  File "/home/user/.virtualenvs/scout/lib/python3.5/copy.py", line 89, in copy
    return copier(x)
  File "/home/user/.virtualenvs/scout/lib/python3.5/site-packages/orator/orm/builder.py", line 1171, in __copy__
    new = self.__class__(copy.copy(self._query))
  File "/home/user/.virtualenvs/scout/lib/python3.5/copy.py", line 89, in copy
    return copier(x)
  File "/home/user/.virtualenvs/scout/lib/python3.5/site-packages/orator/query/builder.py", line 1674, in __copy__
    in copy.deepcopy(self.__dict__).items()
  File "/home/user/.virtualenvs/scout/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/home/user/.virtualenvs/scout/lib/python3.5/copy.py", line 244, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/user/.virtualenvs/scout/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/home/user/.virtualenvs/scout/lib/python3.5/copy.py", line 298, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/user/.virtualenvs/scout/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/home/user/.virtualenvs/scout/lib/python3.5/copy.py", line 244, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/user/.virtualenvs/scout/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/home/user/.virtualenvs/scout/lib/python3.5/copy.py", line 298, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/user/.virtualenvs/scout/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/home/user/.virtualenvs/scout/lib/python3.5/copy.py", line 244, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/user/.virtualenvs/scout/lib/python3.5/copy.py", line 174, in deepcopy
    rv = reductor(4)
```

And, I was trying it without using ```.first_or_new()```, and did like this...

```python
team = Team()
# team.foo = 'bar';
team.save()
```

... and it generates the following exception + traceback:

**TypeError: Cannot serialize socket object**

```
Traceback (most recent call last):
  File "/home/user/python-projects/scout/scout_app/cli_app.py", line 24, in update_teams
    team.save()
  File "/home/user/.virtualenvs/scout/lib/python3.5/site-packages/orator/orm/model.py", line 1512, in save
    saved = self._perform_insert(query, options)
  File "/home/user/.virtualenvs/scout/lib/python3.5/site-packages/orator/orm/model.py", line 1583, in _perform_insert
    self._insert_and_set_id(query, attributes)
  File "/home/user/.virtualenvs/scout/lib/python3.5/site-packages/orator/orm/model.py", line 1605, in _insert_and_set_id
    id = query.insert_get_id(attributes, key_name)
  File "/home/user/.virtualenvs/scout/lib/python3.5/site-packages/orator/orm/builder.py", line 1168, in __getattr__
    return self.__dynamic(item)
  File "/home/user/.virtualenvs/scout/lib/python3.5/site-packages/orator/orm/builder.py", line 1145, in __dynamic
    attribute = getattr(self.apply_scopes().get_query(), method)
  File "/home/user/.virtualenvs/scout/lib/python3.5/site-packages/orator/orm/builder.py", line 936, in apply_scopes
    builder = copy.copy(self)
  File "/home/user/.virtualenvs/scout/lib/python3.5/copy.py", line 89, in copy
    return copier(x)
  File "/home/user/.virtualenvs/scout/lib/python3.5/site-packages/orator/orm/builder.py", line 1171, in __copy__
    new = self.__class__(copy.copy(self._query))
  File "/home/user/.virtualenvs/scout/lib/python3.5/copy.py", line 89, in copy
    return copier(x)
  File "/home/user/.virtualenvs/scout/lib/python3.5/site-packages/orator/query/builder.py", line 1674, in __copy__
    in copy.deepcopy(self.__dict__).items()
  File "/home/user/.virtualenvs/scout/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/home/user/.virtualenvs/scout/lib/python3.5/copy.py", line 244, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/user/.virtualenvs/scout/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/home/user/.virtualenvs/scout/lib/python3.5/copy.py", line 298, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/user/.virtualenvs/scout/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/home/user/.virtualenvs/scout/lib/python3.5/copy.py", line 244, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/user/.virtualenvs/scout/lib/python3.5/copy.py", line 182, in deepcopy
    y = _reconstruct(x, rv, 1, memo)
  File "/home/user/.virtualenvs/scout/lib/python3.5/copy.py", line 298, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/user/.virtualenvs/scout/lib/python3.5/copy.py", line 155, in deepcopy
    y = copier(x, memo)
  File "/home/user/.virtualenvs/scout/lib/python3.5/copy.py", line 244, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/user/.virtualenvs/scout/lib/python3.5/copy.py", line 174, in deepcopy
    rv = reductor(4)
  File "/usr/lib/python3.5/socket.py", line 175, in __getstate__
    raise TypeError("Cannot serialize socket object")
```

Thanks in advance!

**Comment by joaobarbosa** [comment]
Testing other cases, I found out that when the database record already exists, saving after fetch it using ```.find_or_new()``` works fine. :+1:

**Comment by joaobarbosa** [comment]
Testing again:

Installing from straight from git, it works! I did it with two branches:

```
git+https://github.com/sdispater/orator.git@0.8
git+https://github.com/sdispater/orator.git@develop
```

Problem is only happening with the stable release/tag 0.8.1.

**Comment by sdispater** [comment]
Thanks for the thorough investigation 👏 

I should release the `0.8.2` version this week with this fix included.

**Comment by sdispater** [comment]
Version `0.8.2` has just been released.
